name: Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: cp1.awardspace.net
          username: 4431943_admin
          password: exampleexample13
          protocol: ftp
          port: 221
